alias: 'Flic Wit lang'
hide_entity: false
trigger:
    - platform: event
      event_type: flic_click
      event_data:
       button_name: flic_80e4da71e846
       click_type: hold
action:
      - service: scene.turn_on
        entity_id:
          - scene.slaapkamer_oost_fel
