alias: 'Flic Wit enkel'
hide_entity: false
trigger:
    - platform: event
      event_type: flic_click
      event_data:
       button_name: flic_80e4da71e846
       click_type: single
action:
      - service: light.toggle
        entity_id:
          - light.slaapkamer_oost
          - light.plafondlamp_slaapkamer_oost_level_7_0_2
