alias: 'Lampen eettafel uit'
hide_entity: false
trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
       object_id: zonwering_zuid_3
       scene_id: 25
action:
      - service: light.turn_off
        entity_id:
          - light.hanglampen_eettafel
