alias: 'Zonwering alles omhoog'
hide_entity: false
trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
       object_id: zonwering_zuid
       scene_id: 12
    - platform: event
      event_type: zwave.scene_activated
      event_data:
       object_id: zonwering_oost_links
       scene_id: 12
    - platform: event
      event_type: zwave.scene_activated
      event_data:
       object_id: zonwering_oost_rechts
       scene_id: 12
action:
      - service: script.turn_on
        entity_id:
          - script.zonwering_omhoog
